
services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: dip2003/chatback
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/ChatApp
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mongo-db:

networks:
  app-network:
